### PR TITLE
New API: from actor for session backend

### PR DESCRIPTION
**Pull request by KeenS**
Current API creates redis actor internally.
This patch enables user to create session backend from (address of) actor, which helps reducing the number of connections.

### CODE REVIEW

**Comment by KeenS** [comment]
@pandaman64 :pray:

**Review by pandaman64 — CHANGES_REQUESTED** [review]
Can you reword doc comments a bit so that users don't mix up IP addresses of Redis servers with actor addresses?

**Comment by KeenS** [comment]
I guess its clear by type, but I follow your advice. Wait a moment.

**Comment by KeenS** [comment]
BTW, `addr` of `new` / `new_cluster` is not an address because it includes the port number. How about calling it `server` ?

**Comment by pandaman64** [comment]
Thanks. I agree with that it's obvious from the signature, but just in case.

**Pull request merged**
